env:
  browser: true
  amd: true
  node: true
  es6: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
    esversion: 6
  sourceType: module
plugins:
  - react
  - testing-library
rules: {}
