version: "3"
services:
  # For installing gems:
  # docker-compose run --rm web bundle install --jobs 20 --retry 5
  web:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/myapp
      - /myapp/tmp/pids
      - bundle-datavolume:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  webpack:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    command: >
      sh -c "yarn &&
             bin/webpack-dev-server"
    volumes:
      - .:/myapp
      - node-datavolume:/myapp/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - web
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: Vantage
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root

volumes:
  mysql-datavolume:
  bundle-datavolume:
  node-datavolume:
