version: "3"
services:
  # For installing gems:
  # docker-compose run --rm web bundle install --jobs 20 --retry 5
  web:
    image: ${DOCKER_IMAGE_NAME-vantage}
    build:
      context: .
      args:
        precompileassets: 'not'
    links:
      - mysql
      - webpacker
    ports:
      - 3000:3000
    command: ["./scripts/wait-for-it.sh", "db:3306", "--", "./scripts/start_rails.sh"]
    volumes:
      - .:/opt/vantage:cached

  webpacker:
    image: ${DOCKER_IMAGE_NAME-vantage}
    command: ["./scripts/start_webpack_dev.sh"]
    volumes:
      - .:/opt/vantage:cached
    ports:
      - 3035:3035

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
