default: &default
  db_host: <%= ENV["DB_HOST"] || "127.0.0.1" %>
  db_username: <%= ENV["DB_USERNAME"] || "root" %>
  db_password: <%= ENV["DB_PASSWORD"] || "root" %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

sandbox:
  <<: *default

auditor:
  <<: *default

worker:
  <<: *default

production:
  <<: *default