# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || SecureRandom.hex(64) %>
  #-------------------------------------------------------------------------------------------------------
  # DATABASE
  db_host: <%= ENV["DB_HOST"] || "127.0.0.1" %>
  db_name: <%= ENV["DB_NAME"] || "Vantage_development" %>
  db_username: <%= ENV["DB_USERNAME"] || "root" %>
  db_password: <%= ENV["DB_PASSWORD"] || "root" %>
  # Sidekiq uses 15 threads in production. This value should be more than the largest
  # number of threads that any of the processes run in order to not run out
  # FIXME: This value should not be hard coded but computed based on other values
  db_pool: <%= ENV["DB_POOL"] || 30 %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

sandbox:
  <<: *default

auditor:
  <<: *default

worker:
  <<: *default

# Do not keep production secrets in the repository, instead read values from the environment.
production:
  <<: *default
